stages:
  - test

test:
  image:
    name: chronos86/visual-regression:1.0.0
    entrypoint: [""]
  stage: test
  script:
    - echo "start"
    - cd /src
    - ./entrypoint4.sh
    - cypress run --project /builds/gkudlinski/visual-regression
    - echo "the end"